name: hushh_agent_app
description: "Hushh Agent Application - Business management platform for agents"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter

  # ===== CORE DEPENDENCIES =====
  cupertino_icons: ^1.0.6
  
  # ===== STATE MANAGEMENT =====

  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
  # ===== DEPENDENCY INJECTION =====
  get_it: ^7.6.4
  injectable: ^2.3.2
  
  # ===== NAVIGATION =====
  go_router: ^12.1.3
  
  # ===== TEXT INPUT =====
  mask_text_input_formatter: ^2.5.0
  pin_code_fields: ^8.0.1
  page_transition: ^2.1.0
  
  # ===== FIREBASE INTEGRATION =====
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10
  firebase_messaging: ^15.2.10
  firebase_analytics: ^11.6.0
  firebase_crashlytics: ^4.3.10
  firebase_performance: ^0.10.1+10
  firebase_remote_config: ^5.5.0
  firebase_app_check: ^0.3.2+10
  
  # ===== HTTP & API =====
  dio: ^5.3.3
  retrofit: ^4.0.3
  pretty_dio_logger: ^1.3.1
  connectivity_plus: ^5.0.2
  http: ^1.1.2
  
  # ===== LOCAL STORAGE =====
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  
  # ===== UI COMPONENTS =====
  flutter_svg: ^2.0.9







  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^2.7.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_slidable: ^3.0.1
  pull_to_refresh: ^2.0.0
  responsive_sizer: ^3.3.0+1
  
  # ===== FORMS & VALIDATION =====
  reactive_forms: ^16.1.1
  formz: ^0.6.1
  email_validator: ^2.1.17
  
  # ===== IMAGE & FILE HANDLING =====
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  permission_handler: ^11.3.1
  
  # ===== CHARTS & ANALYTICS =====
  fl_chart: ^0.65.0
  syncfusion_flutter_charts: ^30.1.41
  
  # ===== BUSINESS FEATURES =====
  barcode_widget: ^2.0.3
  qr_code_scanner: ^1.0.1
  pdf: ^3.10.7
  printing: ^5.11.1
  excel: ^2.1.0
  
  # ===== CHAT & COMMUNICATION =====
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.10
  
  # ===== LOCATION & MAPS =====
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  google_maps_flutter: ^2.9.0
  location: ^8.0.1
  
  # ===== NOTIFICATIONS =====
  flutter_local_notifications: ^19.4.0
  toastification: ^3.0.3
  
  # ===== DATE & TIME =====
  intl: ^0.20.2
  
  # ===== ANIMATIONS =====
  flutter_animate: ^4.5.0
  fadingpageview: ^1.0.0
  
  # ===== AI & GEMINI INTEGRATION =====
  flutter_gemini: ^2.0.4
  
  # ===== BACKGROUND SERVICES =====
  flutter_fgbg: ^0.3.0
  
  # ===== DEVICE FEATURES =====
  device_info_plus: ^11.5.0
  package_info_plus: ^8.3.0
  
  # ===== DEBUGGING & MONITORING =====
  talker_flutter: ^3.5.2
  wiredash: ^2.1.0
  device_preview: ^1.1.0
  
  # ===== UTILITIES =====
  uuid: ^4.2.1
  crypto: ^3.0.3
  logger: ^2.0.2+1
  url_launcher: ^6.2.1
  receive_sharing_intent: ^1.4.5
  
  # ===== WEB INTEGRATION =====
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # ===== CODE GENERATION =====
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1
  hive_generator: ^2.0.1
  retrofit_generator: ^8.0.4
  
  # ===== TESTING =====
  bloc_test: ^9.1.5
  mocktail: ^1.0.2
  
  # ===== LINTING =====
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/fonts/
    - assets/splash-anim.json
    - assets/splash.gif
    - assets/app-logo.png
    - assets/dashboard_bottom_bar_icon.svg
    - assets/profile_bottom_bar_icon.svg
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/inter.ttf
    
    - family: Figtree
      fonts:
        - asset: assets/fonts/Figtree/Figtree-Bold.ttf
          weight: 700
        - asset: assets/fonts/Figtree/Figtree-Italic.ttf
          style: italic
        - asset: assets/fonts/Figtree/Figtree-Light.ttf
          weight: 300































