// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8w_jXmgx2aSqrLdBdPWL8Zzl6JzFq-qE',
    appId: '1:53407187172:web:00758b5c83efe7adb32cf1',
    messagingSenderId: '53407187172',
    projectId: 'hushone-app',
    authDomain: 'hushone-app.firebaseapp.com',
    storageBucket: 'hushone-app.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8w_jXmgx2aSqrLdBdPWL8Zzl6JzFq-qE',
    appId: '1:53407187172:android:6f3e2b29617cd47ab32cf1',
    messagingSenderId: '53407187172',
    projectId: 'hushone-app',
    storageBucket: 'hushone-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8w_jXmgx2aSqrLdBdPWL8Zzl6JzFq-qE',
    appId: '1:53407187172:ios:a77f9f5ee0e15396b32cf1',
    messagingSenderId: '53407187172',
    projectId: 'hushone-app',
    storageBucket: 'hushone-app.appspot.com',
    iosBundleId: 'com.hushh.agent.app',
  );
} 