name: iOS CI/CD to TestFlight

on:
  push:
    branches:
      - production

  pull_request:
    branches:
      - production

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.8' # or latest stable

    - name: Install dependencies
      run: flutter pub get

    - name: Build iOS dependencies
      run: flutter build ios --release --no-codesign

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1

    - name: Install Fastlane
      run: |
        cd ios
        gem install bundler
        bundle install

    - name: Decode API Key
      run: |
        echo "${{ secrets.APP_STORE_CONNECT_KEY }}" | base64 --decode > ios/AuthKey.p8

    - name: Upload to TestFlight
      env:
        APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
        APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        APP_STORE_CONNECT_KEY: ${{ secrets.APP_STORE_CONNECT_KEY }}
      run: |
        cd ios
        bundle exec fastlane beta
